### ISSUE TITLE
The script is not readable

### ISSUE THREAD

**Issue by funtomic** [Matthewspear/OFList#1]

**Comment by matthewspear** [comment]
In what way?

Grab a clone / download the zip 
open the .scpt file it in script editor

Works fine for me!

**Comment by funtomic** [comment]
Script editor doesn't work.
Opened in TextEdit shows only hieroglyphics
![bildschirmfoto 2015-07-08 um 16 09 29](https://cloud.githubusercontent.com/assets/13236006/8572222/8c962bec-258b-11e5-8bba-47d5bb6102e7.png)

**Comment by matthewspear** [comment]
What happens when you try opening in script editor?

**Comment by funtomic** [comment]
error message: the document could not be opened

**Comment by hepplerj** [comment]
I'm getting the same problem re: ScriptEditor unable to open the file. Opening the file in vim gives nothing but glyphs.

**Comment by chrisfsmith** [comment]
Same problem here. GitHub says the file is binary.

**Comment by matthewspear** [comment]
This is the contents of the script:

``` AppleScript
(*
File: OFList.scpt
Revision: 1.0
Revised: 2015-07-07
Author: Matt Spear

Summary: Create taskpaper list of flagged tasks

-----------------------------------------------------------

Script based on Jason Verly's OmniFocus_Due_List.scpt:
http://mygeekdaddy.net/2015/07/03/getting-my-daily-to-do-list-out-of-omnifocus/

*)

--Set Date Functions
set CurrDate to date (short date string of (current date))
set CurrDatetxt to short date string of date (short date string of (current date))

set endDate to (current date) + (7 * days)
set endDatetxt to date (short date string of (endDate))

set dateYeartxt to year of (current date) as integer
set dateMonthtxt to month of (current date) as integer
set dateDaytxt to day of (current date) as integer

if dateMonthtxt < 10 then
    set dateMonthtxt to "0" & dateMonthtxt
end if

if dateDaytxt < 10 then
    set dateDaytxt to "0" & dateDaytxt
end if

try

    --Set File/Path name of MD file
    set theFilePath to choose file name default name "To Do List for " & dateYeartxt & "-" & dateMonthtxt & "-" & dateDaytxt & ".md"

    --Get OmniFocus task list
    set due_Tasks to my OmniFocus_task_list()

on error number -128

    -- do nothing
    return

end try

--Output .MD text file
my write_File(theFilePath, due_Tasks)

--Set OmniFocus Due Task List
on OmniFocus_task_list()
    set CurrDatetxt to short date string of date (short date string of (current date))
    tell application id "com.omnigroup.OmniFocus2"
        tell default document

            set refDueTaskList to a reference to (flattened tasks where (flagged is true and completed is false and (defer date < (current date) or defer date is missing value)))

            set {lstName, lstContext, lstProject} to {name, name of its context, name of its containing project} of refDueTaskList

            set strText to "To Do List for " & CurrDatetxt & ":" & return & return

            repeat with iTask from 1 to count of lstName
                set {strName, varContext, varProject} to {item iTask of lstName, item iTask of lstContext, item iTask of lstProject}
                set strText to strText & "▢ " & strName
                if varContext is not missing value then set strText to strText & " @" & varContext
                if varProject is not missing value then set strText to strText & " (" & varProject & ")"
                set strText to strText & return
            end repeat

        end tell
    end tell
    strText
end OmniFocus_task_list

--Export Task list to .MD file
on write_File(theFilePath, due_Tasks)
    set theText to due_Tasks
    set theFileReference to open for access theFilePath with write permission
    write theText to theFileReference as «class utf8»
    close access theFileReference
end write_File
```

Would someone be able to write this to file and send it over to me (!http://dbinbox.com/matthewspear) - so I can work out what I'm doing wrong!

Thanks,

Matt

**Comment by chrisfsmith** [comment]
I sent OFList-1.scpt

**Comment by matthewspear** [comment]
Can you confirm this version works? - https://dl.dropboxusercontent.com/u/8675353/OFList.scpt

**Comment by chrisfsmith** [comment]
Yes, I can read that file.

**Comment by matthewspear** [comment]
Perfect thanks Chris - I've pushed the update to master!

**Comment by chrisfsmith** [comment]
Turns out I get `script error: Can’t get year of (current date). Access not allowed. (-1723)` when I run the script from within OmniFocus (MAS version) unless the script has been compiled (the binary version you had previously). I assume this is an issue only for the MAS version. I would leave the script as readable text and add a note to the README about needing to edit the bundle id (as mention [here](http://mygeekdaddy.net/2015/07/03/getting-my-daily-to-do-list-out-of-omnifocus/)) and compile it (from within Script Editor).

**Comment by matthewspear** [comment]
Sorry about all these errors etc, this is my first project on github people have started using so I getting to grips with thinking about different versions etc

I think I'll make a setup text which hold user settings like which version it is and will allow for the script to be developed further - I really want to add a set path option so I can schedule it to deliver to my desktop daily without prompts!
